version: '3.2'

services:
  coordinator:
    container_name: coordinator
    image: "pl.battleships/vue-coordinator"
    depends_on:
      - redteam
      - blueteam
    build: coordinator/vueCoordinator
    ports:
      - 8080:80

  blueteam:
    image: pl.battleships/java-spring-ship
    build: javaSpringShip/
    container_name: blueteam
    ports:
      - 8050:8050
      - 8150:8150
    environment:
      SERVER_PORT: 8050
      GEAM_TEAM: blue
      GAME_OPPONENTURL: http://redteam:8051
      GAME_SLEEP: 50
     

  redteam:
    image: pl.battleships/java-spring-ship
    build: javaSpringShip/
    container_name: redteam
    ports:
      - 8051:8051
      - 8151:8151
    environment:
      SERVER_PORT: 8051
      GEAM_TEAM: red
      GAME_OPPONENTURL: http://blueteam:8050
      GAME_SLEEP: 50


